apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c1-cluster-create
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-c1.yaml
    path: mgmt
    repoURL: https://github.com/mansong1/sturdy-disco.git
    targetRevision: HEAD